development:
  adapter: redis
  username: default
  password: <%= ENV['REDIS_PASS'] %>
  host: db-redis-igy6-do-user-14941827-0.c.db.ondigitalocean.com
  port: 25061

test:
  adapter: test

production:
  adapter: redis
  username: default
  password: <%= ENV['REDIS_PASS'] %>
  host: db-redis-igy6-do-user-14941827-0.c.db.ondigitalocean.com
  port: 25061