default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: push_development

test:
  <<: *default
  database: push_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  host     : app-3c42c1fb-6cc6-44f6-b7bf-127ffff59043-do-user-14941827-0.c.db.ondigitalocean.com
  port     : 25060
  username : igy6
  password : <%= ENV["PUSH_DATABASE_PASSWORD"] %>
  database : igy6
  sslmode  : require
